services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sports-events-app
    container_name: sports-events-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - sports-network

  mysql:
    image: mysql:5.7
    container_name: sports-events-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sports
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sports-network

  web:
    image: nginx:latest
    container_name: sports-events-web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www
    networks:
      - sports-network
volumes:
  mysql_data:

networks:
  sports-network: